[workspace]

members = [
    "utils",
    "grid",
    "day01",
    "day02",
    "day03",
    "day04",
    "day05",
    "day06",
    "day07",
    "day08",
]

[profile.release]
codegen-units=1
lto="fat"