name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  AOC:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run tests grid
      run: cargo test --release --no-fail-fast --package=grid
      timeout-minutes: 5

    - name: Run tests utils
      run: cargo test --release --no-fail-fast --package=utils
      timeout-minutes: 5

    - name: Run tests day01
      run: cargo test --release --no-fail-fast --package=day01
      timeout-minutes: 5

    - name: Run tests day02
      run: cargo test --release --no-fail-fast --package=day02
      timeout-minutes: 5

    - name: Run tests day03
      run: cargo test --release --no-fail-fast --package=day03
      timeout-minutes: 5

    - name: Run tests day04
      run: cargo test --release --no-fail-fast --package=day04
      timeout-minutes: 5

    - name: Run tests day05
      run: cargo test --release --no-fail-fast --package=day05
      timeout-minutes: 5

    - name: Run tests day06
      run: cargo test --release --no-fail-fast --package=day06
      timeout-minutes: 5

    - name: Run tests day07
      run: cargo test --release --no-fail-fast --package=day07
      timeout-minutes: 5

    - name: Run tests day08
      run: cargo test --release --no-fail-fast --package=day08
      timeout-minutes: 5

    - name: Run tests day09
      run: cargo test --release --no-fail-fast --package=day09
      timeout-minutes: 5

    - name: Run tests day10
      run: cargo test --release --no-fail-fast --package=day10
      timeout-minutes: 5

    - name: Run tests day11
      run: cargo test --release --no-fail-fast --package=day11
      timeout-minutes: 5

    - name: Run tests day12
      run: cargo test --release --no-fail-fast --package=day12
      timeout-minutes: 5

    - name: Run tests day13
      run: cargo test --release --no-fail-fast --package=day13
      timeout-minutes: 5

    - name: Run tests day14
      run: cargo test --release --no-fail-fast --package=day14
      timeout-minutes: 5

    - name: Run tests day15
      run: cargo test --release --no-fail-fast --package=day15
      timeout-minutes: 5

    - name: Run tests day16
      run: cargo test --release --no-fail-fast --package=day16
      timeout-minutes: 5

    - name: Run tests day17
      run: cargo test --release --no-fail-fast --package=day17
      timeout-minutes: 5

    - name: Run tests day18
      run: cargo test --release --no-fail-fast --package=day18
      timeout-minutes: 5

    - name: Run tests day19
      run: cargo test --release --no-fail-fast --package=day19
      timeout-minutes: 5

    - name: Run tests day20
      run: cargo test --release --no-fail-fast --package=day20
      timeout-minutes: 5

    - name: Run tests day21
      run: cargo test --release --no-fail-fast --package=day21
      timeout-minutes: 5

    - name: Run tests day22
      run: cargo test --release --no-fail-fast --package=day22
      timeout-minutes: 5

    - name: Run tests day23
      run: cargo test --release --no-fail-fast --package=day23
      timeout-minutes: 5

    - name: Run tests day24
      run: cargo test --release --no-fail-fast --package=day24
      timeout-minutes: 5
