name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  AllTests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package: [grid, utils, day01, day02, day03, day04, day05, day06, day07, day08, day09, day10, day11, day12, day13, day14, day15, day16, day17, day18, day19, day20, day21, day22, day23, day24, day25]

    steps:
    - uses: actions/checkout@v3

    - name: Run tests ${{matrix.package}}
      run: cargo test --release --no-fail-fast --package=${{matrix.package}}
      timeout-minutes: 5

